version: '3'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    environment:
      DATABASE_HOSTNAME: postgres
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: